
export const INPUT_MOVIE = "INPUT_MOVIE";
export const FETCH_MOVIE_REQUEST="FETCH_MOVIE_REQUEST";
export const FETCH_MOVIE_SUCCESS="FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_ERROR ="FETCH_MOVIE_ERROR";
export const FETCH_MOVIE = "FETCH_MOVIE";